name: temp-unpublish
on:
  workflow_dispatch:
    branches:
    - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Checkout all branches and tags
    - name: "Use NodeJS 16"
      uses: actions/setup-node@v2
      with: 
        node-version: '16'
    - name: "Version and build"
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
        echo PRE-BOOTSTRAP
        npx lerna bootstrap
        echo POST-BOOTSTRAP
        echo GIT REF:    ${{ github.ref }}
        npx lerna run build --scope=@ircc-ca/ds-sdc-core
        echo core package built
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: "Publishing core"
      working-directory: packages/ds/core/
      run: |
        echo publishing core...
        npm i
        npm set @ircc-ca:registry=https://registry.npmjs.com/
        npm set "//registry.npmjs.com/:_authToken=${{ secrets.NPM_TOKEN }}"
        npm unpublish @ircc-ca/ds-sdc-core@1.0.2 --force
      env:
       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}